name: Playwright TypeScript SauceDemo
on:
  push:
    branch: [ main ]
jobs:
  playwright-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.2-noble
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies from lockfile
        run: npm ci
      - name: Run playwright tests
        run: npm run test:ci